// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using CustomORM.Abstractions;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CustomORM.Core.Entities;

[Table("h_client")]
public partial class HClient : IHub, IAuditLoadInformations
{
    public HClient()
    {
        PClients = new HashSet<PClient>();
        SClientAdresses = new HashSet<SClientAdresse>();
        SClientIdentifications = new HashSet<SClientIdentification>();
    }

    [Key]
    [Column("h_client_hk")]
    [StringLength(64)]
    public string KeyHk { get; set; }

    [Column("h_load_dts")]
    public DateTime LoadDts { get; set; } = DateTime.Now;

    [Column("h_load_user")]
    public string LoadUser { get; set; } = Environment.UserName;

    [Column("h_load_src")]
    public string LoadSrc { get; set; } = AppDomain.CurrentDomain.FriendlyName;

    [Column("no_client")]
    public int FunctionnalKey { get; set; }

    [InverseProperty("HClientHkNavigation")]
    public virtual ICollection<PClient> PClients { get; set; }
    
    [InverseProperty("HClientHkNavigation")]
    public virtual ICollection<SClientAdresse> SClientAdresses { get; set; }
    
    [InverseProperty("HClientHkNavigation")]
    public virtual ICollection<SClientIdentification> SClientIdentifications { get; set; }
}