// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CustomORM.Core.Entities;

[Table("s_client_identification")]
public partial class SClientIdentification
{
    public SClientIdentification()
    {
        PClients = new HashSet<PClient>();
    }

    [Key]
    [Column("h_client_hk")]
    [StringLength(64)]
    public string HClientHk { get; set; }
    
    [Key]
    [Column("s_load_dts", TypeName = "datetime")]
    public DateTime SLoadDts { get; set; }
    
    [Required]
    [Column("s_load_user")]
    [StringLength(10)]
    public string SLoadUser { get; set; }
    
    [Required]
    [Column("s_load_src")]
    [StringLength(10)]
    public string SLoadSrc { get; set; }
    
    [Column("prenom")]
    [StringLength(20)]
    public string Prenom { get; set; }
    
    [Column("nom")]
    [StringLength(20)]
    public string Nom { get; set; }
    
    [Column("sexe")]
    [StringLength(1)]
    public string Sexe { get; set; }
    
    [Column("date_naissance", TypeName = "date")]
    public DateTime? DateNaissance { get; set; }
    
    [Column("date_deces", TypeName = "date")]
    public DateTime? DateDeces { get; set; }
    
    [Column("langue")]
    [StringLength(3)]
    public string Langue { get; set; }

    [ForeignKey("HClientHk")]
    [InverseProperty("SClientIdentifications")]
    public virtual HClient HClientHkNavigation { get; set; }
    
    [InverseProperty("SClientIdentification")]
    public virtual ICollection<PClient> PClients { get; set; }
}
