// <auto-generated> This file has been auto generated by CustomORM.Converter. </auto-generated>
#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace CustomORM.Console.Entities.Relationals;

public sealed class Reclamation
{
    [Key]
    public int NoReclamation { get; set; }

    public string Contenu { get; set; }

    [StringLength(1)]
    public string Priorite { get; set; }
}
