// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CustomORM.Console.Entities.DV2;

[Table("h_client")]
public partial class HClient
{
    public HClient()
    {
        PClients = new HashSet<PClient>();
        SClientAdresses = new HashSet<SClientAdresse>();
        SClientIdentifications = new HashSet<SClientIdentification>();
    }

    [Key]
    [Column("h_client_hk")]
    [StringLength(64)]
    public string HClientHk { get; set; }

    [Column("h_load_dts")]
    public DateTime HLoadDts { get; set; }

    [Column("h_load_user")]
    public string HLoadUser { get; set; }

    [Column("h_load_src")]
    public string HLoadSrc { get; set; }

    [Column("no_client")]
    public int NoClient { get; set; }

    [InverseProperty("HClientHkNavigation")]
    public virtual ICollection<PClient> PClients { get; set; }
    
    [InverseProperty("HClientHkNavigation")]
    public virtual ICollection<SClientAdresse> SClientAdresses { get; set; }
    
    [InverseProperty("HClientHkNavigation")]
    public virtual ICollection<SClientIdentification> SClientIdentifications { get; set; }
}