// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomORM.Console.Entities.DV2;

[Table("l_client_reclamation")]
public partial class LClientReclamation
{
    [Key]
    [Column("l_client_reclamation_hk")]
    [StringLength(64)]
    public string LClientReclamationHk { get; set; }

    [Column("l_load_dts", TypeName = "datetime")]
    public DateTime LLoadDts { get; set; }

    [Required]
    [Column("l_load_user")]
    [StringLength(10)]
    public string LLoadUser { get; set; }

    [Required]
    [Column("l_load_src")]
    [StringLength(10)]
    public string LLoadSrc { get; set; }

    [Required]
    [Column("h_client_hk")]
    [StringLength(64)]
    public string HClientHk { get; set; }

    [Required]
    [Column("h_reclamation_hk")]
    [StringLength(64)]
    public string HReclamationHk { get; set; }

    [ForeignKey("HClientHk")]
    [InverseProperty("LClientReclamations")]
    public virtual HClient HClientHkNavigation { get; set; }

    [ForeignKey("HReclamationHk")]
    [InverseProperty("LClientReclamations")]
    public virtual HReclamation HReclamationHkNavigation { get; set; }

    [InverseProperty("LClientReclamationHkNavigation")]
    public virtual ICollection<PClientReclamation> PClientReclamations { get; set; } = new List<PClientReclamation>();
}