// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomORM.Console.Entities.DV2;

[PrimaryKey("LClientReclamationHk", "PLoadDts")]
[Table("p_client_reclamation")]
public partial class PClientReclamation
{
    [Key]
    [Column("l_client_reclamation_hk")]
    [StringLength(64)]
    public string LClientReclamationHk { get; set; }

    [Key]
    [Column("p_load_dts", TypeName = "datetime")]
    public DateTime PLoadDts { get; set; }

    [Column("p_load_end_dts", TypeName = "datetime")]
    public DateTime? PLoadEndDts { get; set; }

    [Required]
    [Column("p_load_user")]
    [StringLength(10)]
    public string PLoadUser { get; set; }

    [Required]
    [Column("p_load_src")]
    [StringLength(10)]
    public string PLoadSrc { get; set; }

    [ForeignKey("LClientReclamationHk")]
    [InverseProperty("PClientReclamations")]
    public virtual LClientReclamation LClientReclamationHkNavigation { get; set; }
}