// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomORM.Console.Entities.DV2;

[PrimaryKey("HReclamationHk", "PLoadDts")]
[Table("p_reclamation")]
public partial class PReclamation
{
    [Key]
    [Column("h_reclamation_hk")]
    [StringLength(64)]
    public string HReclamationHk { get; set; }

    [Key]
    [Column("p_load_dts", TypeName = "datetime")]
    public DateTime PLoadDts { get; set; }

    [Column("p_load_end_dts", TypeName = "datetime")]
    public DateTime? PLoadEndDts { get; set; }

    [Required]
    [Column("p_load_user")]
    [StringLength(10)]
    public string PLoadUser { get; set; }

    [Required]
    [Column("p_load_src")]
    [StringLength(10)]
    public string PLoadSrc { get; set; }

    [Column("s_info_ldts", TypeName = "datetime")]
    public DateTime? SInfoLdts { get; set; }

    [ForeignKey("HReclamationHk")]
    [InverseProperty("PReclamations")]
    public virtual HReclamation HReclamationHkNavigation { get; set; }

    [ForeignKey("HReclamationHk, SInfoLdts")]
    [InverseProperty("PReclamations")]
    public virtual SReclamationInfo SReclamationInfo { get; set; }
}