// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomORM.Console.Entities.DV2;

[PrimaryKey("HClientHk", "SLoadDts")]
[Table("s_client_adresse")]
public partial class SClientAdresse
{
    [Key]
    [Column("h_client_hk")]
    [StringLength(64)]
    public string HClientHk { get; set; }

    [Key]
    [Column("s_load_dts", TypeName = "datetime")]
    public DateTime SLoadDts { get; set; }

    [Required]
    [Column("s_load_user")]
    public string SLoadUser { get; set; }

    [Required]
    [Column("s_load_src")]
    public string SLoadSrc { get; set; }

    [Column("adresse1")]
    public string Adresse1 { get; set; }

    [Column("adresse2")]
    public string Adresse2 { get; set; }

    [Column("adresse3")]
    public string Adresse3 { get; set; }

    [Required]
    [Column("cite")]
    [StringLength(100)]
    [Unicode(false)]
    public string Cite { get; set; }

    [Required]
    [Column("provence")]
    [StringLength(2)]
    [Unicode(false)]
    public string Provence { get; set; }

    [Required]
    [Column("pays")]
    [StringLength(2)]
    [Unicode(false)]
    public string Pays { get; set; }

    [Required]
    [Column("code_postale")]
    [StringLength(16)]
    [Unicode(false)]
    public string CodePostale { get; set; }

    [ForeignKey("HClientHk")]
    [InverseProperty("SClientAdresses")]
    public virtual HClient HClientHkNavigation { get; set; }

    [InverseProperty("SClientAdresse")]
    public virtual ICollection<PClient> PClients { get; set; } = new List<PClient>();
}