// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomORM.Console.Entities.DV2;

[PrimaryKey("HClientHk", "SLoadDts")]
[Table("s_client_identification")]
public partial class SClientIdentification
{
    [Key]
    [Column("h_client_hk")]
    [StringLength(64)]
    public string HClientHk { get; set; }

    [Key]
    [Column("s_load_dts", TypeName = "datetime")]
    public DateTime SLoadDts { get; set; }

    [Required]
    [Column("s_load_user")]
    public string SLoadUser { get; set; }

    [Required]
    [Column("s_load_src")]
    public string SLoadSrc { get; set; }

    [Column("prenom")]
    public string Prenom { get; set; }

    [Column("nom")]
    public string Nom { get; set; }

    [Column("sexe")]
    [StringLength(1)]
    public string Sexe { get; set; }

    [Column("date_naissance")]
    public DateOnly? DateNaissance { get; set; }

    [Column("date_deces")]
    public DateOnly? DateDeces { get; set; }

    [Column("langue")]
    [StringLength(3)]
    public string Langue { get; set; }

    [ForeignKey("HClientHk")]
    [InverseProperty("SClientIdentifications")]
    public virtual HClient HClientHkNavigation { get; set; }

    [InverseProperty("SClientIdentification")]
    public virtual ICollection<PClient> PClients { get; set; } = new List<PClient>();
}