// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CustomORM.Console.Entities.DV2;

[PrimaryKey("HReclamationHk", "SLoadDts")]
[Table("s_reclamation_info")]
public partial class SReclamationInfo
{
    [Key]
    [Column("h_reclamation_hk")]
    [StringLength(64)]
    public string HReclamationHk { get; set; }

    [Key]
    [Column("s_load_dts", TypeName = "datetime")]
    public DateTime SLoadDts { get; set; }

    [Required]
    [Column("s_load_user")]
    [StringLength(10)]
    public string SLoadUser { get; set; }

    [Required]
    [Column("s_load_src")]
    [StringLength(10)]
    public string SLoadSrc { get; set; }

    [Column("contenu")]
    public string Contenu { get; set; }

    [Column("priorite")]
    [StringLength(1)]
    public string Priorite { get; set; }

    [ForeignKey("HReclamationHk")]
    [InverseProperty("SReclamationInfos")]
    public virtual HReclamation HReclamationHkNavigation { get; set; }

    [InverseProperty("SReclamationInfo")]
    public virtual ICollection<PReclamation> PReclamations { get; set; } = new List<PReclamation>();
}