// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CustomORM.Console.Entities.DV2;

[Keyless]
public partial class VClient
{
    [Column("no_client")]
    public int NoClient { get; set; }

    [Column("prenom")]
    [StringLength(20)]
    public string Prenom { get; set; }

    [Column("nom")]
    [StringLength(20)]
    public string Nom { get; set; }

    [Column("sexe")]
    [StringLength(1)]
    public string Sexe { get; set; }

    [Column("date_naissance", TypeName = "date")]
    public DateTime? DateNaissance { get; set; }

    [Column("date_deces", TypeName = "date")]
    public DateTime? DateDeces { get; set; }

    [Column("langue")]
    [StringLength(3)]
    public string Langue { get; set; }

    [Column("adresse1")]
    public string Adresse1 { get; set; }

    [Column("adresse2")]
    public string Adresse2 { get; set; }

    [Column("adresse3")]
    public string Adresse3 { get; set; }

    [Column("cite")]
    [StringLength(100)]
    public string Cite { get; set; }

    [Column("provence")]
    [StringLength(2)]
    public string Provence { get; set; }

    [Column("pays")]
    [StringLength(2)]
    public string Pays { get; set; }

    [Column("code_postale")]
    [StringLength(16)]
    public string CodePostale { get; set; }
}
